---
name: "MQTT SberGate.OOP"
slug: "mqtt-sber-gate-oop"
version: "1.1.0"
description: "MQTT SberGate SberDevice IoT Agent for Home Assistant. Refactored"
url: "https://gitverse.ru/mberezovsky/MQTT-SberGate.git"
webui: "http://[HOST]:[PORT:9123]"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

ports:
  9123/tcp: 9123
ports_description:
  9123/tcp: Management

options:
  ha-api_url: "http://ha_server_ip:8123"
  ha-api_token: ""
  sber-mqtt_broker: "mqtt-partners.iot.sberdevices.ru"
  sber-mqtt_broker_port: 8883
  sber-mqtt_login: "mqtt-sber-login"
  sber-mqtt_password: "mqtt-sber-password"
  sber-http_api_endpoint: "https://mqtt-partners.iot.sberdevices.ru"
  log_level: INFO

schema:
  ha-api_url: str
  ha-api_token: str
  sber-mqtt_broker: str
  sber-mqtt_broker_port: int
  sber-mqtt_login: str
  sber-mqtt_password: password
  sber-http_api_endpoint: str?
  log_level: list(DEBUG|INFO|WARNING|ERROR|FATAL)
